fix latex compile

diff --git a/compiler b/compiler
--- a/compiler
+++ b/compiler
@@ -14,18 +14,24 @@ dir=${file%/*}
 base="${file%.*}"
 ext="${file##*.}"
 
+# Check if the file exists
+if [ ! -f "$file" ]; then
+  # echo "File '$file' does not exist."
+  exit 1
+fi
+
 cd "$dir" || exit 1
 
 # added delay between the double compile to wait for table of contents file .toc - Tim R
 textype() { \
-	command="pdflatex -interaction=batchmode" # added this to avoid prompt when file not found - Tim R
+	command="pdflatex -interaction=batchmode -recorder -file-line-error" # added batchmode to avoid prompt when file not found - Tim R
 	( head -n5 "$file" | grep -qi 'xelatex' ) && command="xelatex"
-	$command --output-directory="$dir" "$base" &&
+	$command --output-directory="$dir" "$base" > /dev/null &&
 	grep -qi addbibresource "$file" &&
-	biber --input-directory "$dir" "$base" &&
-	$command --output-directory="$dir" "$base" &&
+	biber --input-directory "$dir" "$base" > /dev/null &&
+	$command --output-directory="$dir" "$base" > /dev/null &&
 	sleep 250m &&
-	$command --output-directory="$dir" "$base"
+	$command --output-directory="$dir" "$base" > /dev/null 
 }
 
 case "$ext" in
