working extract

diff --git a/extract b/extract
--- a/extract
+++ b/extract
@@ -14,7 +14,7 @@ extract_file() {
   local file="$1"
   local tool="$2"
   local options="$3"
-  local base="${file%.*}"
+#  local base="${file%.*}"
   
   # make temp dir and move into it
   mkdir temp
@@ -27,7 +27,7 @@ extract_file() {
     exit 1
   fi
   cd ../
-  mv -buv temp/* $base
+  mv -buv temp/* $output_file
   rm -r temp
   echo "File '$file' extracted successfully."
 }
@@ -65,9 +65,17 @@ if [ ! -f "$file" ]; then
   echo "File '$file' does not exist."
   exit 1
 fi
+#
+#|| [ ! -w "$output_file" ]
+if [ ! "$output_file" ] ; then 
+  output_file="${file%.*}"
+fi
 
-if [ ! $output_file ] || [ ! -w $output_file ] ; then 
-  echo 'No output file specified or not writable. Using default'
+if [ ! -d "$output_file" ] ; then 
+  if ! mkdir "$output_file"  ; then
+    echo "Could not create '$output_file'"
+    exit 1
+  fi
 fi
 
 # Determine file extension and extract accordingly
