add TODOs and minor refactoring

diff --git a/extract b/extract
--- a/extract
+++ b/extract
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+#TODO: change wording output file to output path
+
 # Function to display usage
 usage() {
   echo "Usage: $0 [-o output_file] file_name"
@@ -9,27 +11,29 @@ usage() {
   exit 1
 }
 
+#TODO: use global variable for output file
+#TODO: handle exceptions for creating, entering and removing temp dir
 # Extract function for different file types
 extract_file() {
-  local file="$1"
-  local tool="$2"
-  local options="$3"
-#  local base="${file%.*}"
+  _file="$1"
+  _tool="$2"
+  _options="$3"
+#  _base="${file%.*}"
   
-  # make temp dir and move into it
-  mkdir temp
-  cd temp
+  # make new dir temp,if successful move into it otherwise exit 1
+  mkdir temp && cd temp || exit 1
 
-  if ! "$tool" $options "../$file"; then
+  if ! "$_tool" "$_options" "../$_file"; then
     cd ../
     rm -fr temp
-    echo "Extraction failed or not possible for file '$file'."
+    echo "Extraction failed or not possible for file '$_file'."
     exit 1
   fi
+  # clean up
   cd ../
-  mv -buv temp/* $output_file
+  mv -buv temp/* "$output_file"
   rm -r temp
-  echo "File '$file' extracted successfully."
+  echo "File '$_file' extracted successfully."
 }
 
 # Check if any arguments provided
@@ -40,6 +44,8 @@ fi
 # Variables for output file
 output_file=""
 
+#TODO: add a silent option -s. If this option is set all output is suppressed. 
+#TODO: ensure exit 1 on all errors/exceptions
 # Parse command options
 while getopts "o:h" opt; do
   case $opt in
@@ -65,7 +71,7 @@ if [ ! -f "$file" ]; then
   echo "File '$file' does not exist."
   exit 1
 fi
-#
+
 #|| [ ! -w "$output_file" ]
 if [ ! "$output_file" ] ; then 
   output_file="${file%.*}"
@@ -78,6 +84,7 @@ if [ ! -d "$output_file" ] ; then
   fi
 fi
 
+#TODO: don't pass $file use global variable
 # Determine file extension and extract accordingly
 case "$file" in
   *.tar.bz2)
@@ -118,20 +125,5 @@ esac
 
 echo "Have a nice day!"
 
-# dir="${file%/*}"
-# base="${file%.*}"
-# ext="${file##*.}"
-# echo $dir
-# echo $base
-# echo $ext
-#
-# if [ -d temp ]; then
-#   mv -buv temp $base
-# fi
-#
-#
-# # Rename extracted file if output file specified
-# if [ -n "$output_file" ]; then
-#   mv "$file" "$output_file"
-# fi
+
 
